esphome:
  # This will allow for project identification,
  # configuration and updates.
  name: ltesop1meterreader
  project:
    name: modo.p1meter_lt_eso
    version: dev # This will be replaced by the github workflows with the `release` version

# This should point to the public location of the yaml file that will be adopted.
# In this case it is the core yaml file that does not contain the extra things
# that are provided by this factory yaml file as the user does not need these once adopted.
dashboard_import:
  package_import_url: github://mmodestas/modop1/main/modop1-d1mini.yaml@main

esp8266:
  board: d1_mini
logger:
  baud_rate: 0
  level: ERROR
  esp8266_store_log_strings_in_flash: false
  tx_buffer_size: 64

api:

ota:
  - platform: esphome

wifi:
  ap:
    ssid: "P1 Meter LT ESO Hotspot"
    password: "Welcome2!"

# Sets up the improv via serial client for Wi-Fi provisioning.
# Handy if your device has a usb port for the user to add credentials when they first get it.
#improv_serial:

captive_portal:

web_server:
  port: 80

uart:
  id: p1_uart
  rx_pin:
    number: 3
    inverted: true
  rx_buffer_size: 512
  baud_rate: 115200

time:
  - platform: homeassistant
    id: homeassistant_time

dsmr:
  uart_id: p1_uart
  max_telegram_length: 3000
  receive_timeout: 200ms

text_sensor:
  - platform: version
    name: ESPHome Version
#  - platform: debug
#    reset_reason:
#      name: "Reset Reason"    
  - platform: dsmr
    identification:
      name: "DSMR Identification"
    p1_version:
      name: "DSMR Version"
# Sensor to store parsed telegram data 
    telegram:
      name: dsmr_telegram
sensor:
  - platform: uptime
    name: ESO Device Uptime
    type: seconds
    update_interval: 60s
  - platform: wifi_signal
    name: WiFi Signal
    update_interval: 60s
  - platform: dsmr
    energy_delivered_lux:
      name: ESO Active energy import (+A)
#       name: energy_delivered_lux
#      filters:
#        - throttle: 15s
    energy_delivered_tariff1:
      name: ESO Active energy import (+A) rate 1
#      filters:
#        - throttle: 15s
    energy_delivered_tariff2:
      name: ESO Active energy import (+A) rate 2
#      filters:
#        - throttle: 15s
    energy_returned_lux:
      name: ESO Active energy export (-A)
#       name: energy_returned_lux
#      filters:
#        - throttle: 15s
    power_delivered:
      name: ESO Inst active import power (+A)
#     name: power_delivered
#      filters:
#        - throttle: 15s
    power_returned:
      name: ESO Inst active export power (-A)
#       name: power_returned
#      filters:
#        - throttle: 15s
    power_delivered_l1:
      name: ESO Inst active import power (+A) in phase L1 [kW]
#       name: power_delivered_l1
#      filters:
#        - throttle: 15s
    power_delivered_l2:
      name: ESO Inst active import power (+A) in phase L2 [kW]
#       name: power_delivered_l2
#      filters:
#        - throttle: 15s
    power_delivered_l3:
      name: ESO Inst active import power (+A) in phase L3 [kW]
#      filters:
#        - throttle: 15s
    power_returned_l1:
      name: ESO Inst active export power (-A) in phase L1 [kW]
#       name: power_returned_l1
#      filters:
#        - throttle: 15s
    power_returned_l2:
      name: ESO Inst active export power (-A) in phase L2 [kW]
#      filters:
#        - throttle: 15s
    power_returned_l3:
      name: ESO Inst active export power (-A) in phase L3 [kW]
#      filters:
#        - throttle: 15s
    voltage_l1:
      name: ESO Inst voltage L1
#      filters:
#        - throttle: 30s
    voltage_l2:
      name: ESO Inst voltage L2
#      filters:
#        - throttle: 30s
    voltage_l3:
      name: ESO Inst voltage L3
#      filters:
#        - throttle: 30s
    current_l1:
      name: ESO Inst current L1
#      filters:
#        - throttle: 30s
    current_l2:
      name: ESO Inst current L2
#      filters:
#        - throttle: 30s
    current_l3:
      name: ESO Inst current L3
#      filters:
#        - throttle: 30s

#debug:
#  update_interval: 5s
