esphome:
  name: modop1
  friendly_name: Modo P1 Reader (LT-ESO)
  name_add_mac_suffix: false
  project:
    name: modo.p1_reader_lt_eso
    version: dev # This will be replaced by the github workflows with the `release` version
    
# This should point to the public location of the yaml file that will be adopted.
# In this case it is the core yaml file that does not contain the extra things
# that are provided by this factory yaml file as the user does not need these once adopted.
dashboard_import:
  package_import_url: github://mmodestas/modop1/modop1-d1mini.yaml@main

esp8266:
  board: d1_mini
logger:
  baud_rate: 0
  level: ERROR
  esp8266_store_log_strings_in_flash: false
  tx_buffer_size: 64

api:

ota:
  - platform: esphome

wifi:
  ap:

# Sets up the improv via serial client for Wi-Fi provisioning.
# Handy if your device has a usb port for the user to add credentials when they first get it.
#improv_serial:

captive_portal:

web_server:
  port: 80

#debug:
#  update_interval: 5s

uart:
  id: p1_uart
  rx_pin:
    number: 3
    inverted: true
  rx_buffer_size: 512
  baud_rate: 115200

time:
  - platform: homeassistant
    id: homeassistant_time

dsmr:
  uart_id: p1_uart
  max_telegram_length: 3000
  receive_timeout: 200ms

text_sensor:
  - platform: version
    name: ESPHome Version
#  - platform: debug
#    reset_reason:
#      name: "Reset Reason"    
  - platform: dsmr
    identification:
      name: "DSMR Identification"
    p1_version:
      name: "DSMR Version"
# Sensor to store parsed telegram data 
    telegram:
      name: dsmr_telegram
sensor:
  - platform: uptime
    name: P1 Device Uptime
    type: seconds
    update_interval: 60s
  - platform: wifi_signal
    name: WiFi Signal
    update_interval: 60s
  - platform: dsmr
    energy_delivered_lux:
      name: ESO Active energy import (+A)
      id: p1_active_energy_import

    energy_delivered_tariff1:
      name: ESO Active energy import (+A) rate 1
      id: p1_active_energy_import_rate_1

    energy_delivered_tariff2:
      name: ESO Active energy import (+A) rate 2
      id: p1_active_energy_import_rate_2

    energy_returned_lux:
      name: ESO Active energy export (-A)
      id: p1_active_energy_export

    power_delivered:
      name: P1 Instantaneous active import power (+A)
      id: p1_instantaneous_active_import_power

    power_returned:
      name: ESO Instantaneous active export power (-A)
      id: p1_instantaneous_active_export_power

    power_delivered_l1:
      name: ESO Instantaneous active import power (+A) in phase L1 [kW]
      id: p1_instantaneous_active_import_power_in_phase_l1

    power_delivered_l2:
      name: ESO Instantaneous active import power (+A) in phase L2 [kW]
      id: p1_instantaneous_active_import_power_in_phase_l2

    power_delivered_l3:
      name: ESO Instantaneous active import power (+A) in phase L3 [kW]
      id: p1_instantaneous_active_import_power_in_phase_l3

    power_returned_l1:
      name: P1 Instantaneous active export power (-A) in phase L1 [kW]
      id: p1_instantaneous_active_export_power_in_phase_l1

    power_returned_l2:
      name: P1 Instantaneous active export power (-A) in phase L2 [kW]
      id: p1_instantaneous_active_export_power_in_phase_l2

    power_returned_l3:
      name: P1 Instantaneous active export power (-A) in phase L3 [kW]
      id: p1_instantaneous_active_export_power_in_phase_l3

    voltage_l1:
      name: P1 Instantaneous voltage L1
      id: p1_instantaneous_voltage_l1

    voltage_l2:
      name: ESO Instantaneous voltage L2
      id: p1_instantaneous_voltage_l2

    voltage_l3:
      name: P1 Instantaneous voltage L3
      id: p1_instantaneous_voltage_l3

    current_l1:
      name: P1 Instantaneous current L1
      id: p1_instantaneous_current_l1

    current_l2:
      name: P1 Instantaneous current L2
      id: p1_instantaneous_current_l2

    current_l3:
      name: P1 Instantaneous current L3
      id: p1_instantaneous_current_l3
