esphome:
  name: modop1reader
  friendly_name: Modo P1 Reader
  name_add_mac_suffix: false
  project:
    name: modo.p1reader_lt_eso
    version: dev
dashboard_import:
  package_import_url: github://mmodestas/modop1/modop1-d1mini.yaml@main
esp8266:
  board: d1_mini
logger:
  baud_rate: 0
  level: ERROR
  esp8266_store_log_strings_in_flash: false
  tx_buffer_size: 64
api: null
ota:
  - platform: esphome
wifi:
  ap:
captive_portal: null
web_server:
  port: 80
uart:
  id: p1_uart
  rx_pin:
    number: 3
    inverted: true
  rx_buffer_size: 512
  baud_rate: 115200
time:
  - platform: homeassistant
    id: homeassistant_time
dsmr:
  uart_id: p1_uart
  max_telegram_length: 3000
  receive_timeout: 200ms
text_sensor:
  - platform: version
    name: ESPHome Version
  - platform: dsmr
    identification:
      name: DSMR Identification
    p1_version:
      name: DSMR Version
    telegram:
      name: dsmr_telegram
sensor:
  - platform: uptime
    name: ESO Device Uptime
    type: seconds
    update_interval: 60s
  - platform: wifi_signal
    name: WiFi Signal
    update_interval: 60s
  - platform: dsmr
    energy_delivered_lux:
      name: P1 ESO Active energy import (+A)
      id: p1_active_energy_import
    energy_delivered_tariff1:
      name: P1 ESO Active energy import (+A) rate 1
      id: p1_active_energy_import_rate1
    energy_delivered_tariff2:
      name: P1 ESO Active energy import (+A) rate 2
      id: p1_active_energy_import_rate2
    energy_returned_lux:
      name: P1 ESO Active energy export (-A)
      id: p1_active_energy_export
    power_delivered:
      name: P1 ESO Inst active import power (+A)
      id: p1_inst_active_import_power
    power_returned:
      name: P1 ESO Inst active export power (-A)
      id: p1_inst_active_export_power
    power_delivered_l1:
      name: P1 ESO Inst active import power (+A) in phase L1 [kW]
      id: p1_inst_active_import_power_phase1
    power_delivered_l2:
      name: P1 ESO Inst active import power (+A) in phase L2 [kW]
      id: p1_inst_active_import_power_phase2
    power_delivered_l3:
      name: P1 ESO Inst active import power (+A) in phase L3 [kW]
      id: p1_inst_active_import_power_phase3
    power_returned_l1:
      name: P1 ESO Inst active export power (-A) in phase L1 [kW]
      id: p1_inst_active_export_power_phase1
    power_returned_l2:
      name: P1 ESO Inst active export power (-A) in phase L2 [kW]
      id: p1_inst_active_export_power_phase2
    power_returned_l3:
      name: P1 ESO Inst active export power (-A) in phase L3 [kW]
      id: p1_inst_active_export_power_phase3
    voltage_l1:
      name: P1 ESO Inst voltage L1
      id: p1_inst_voltage_l1
    voltage_l2:
      name: P1 ESO Inst voltage L2
      id: p1_inst_voltage_l2
    voltage_l3:
      name: P1 ESO Inst voltage L3
      id: p1_inst_voltage_l3
    current_l1:
      name: P1 ESO Inst current L1
      id: p1_inst_current_l1
    current_l2:
      name: P1 ESO Inst current L2
      id: p1_inst_current_l2
    current_l3:
      name: P1 ESO Inst current L3
      id: p1_inst_current_l3
